<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="0" tests="21" name="test.TestCases" time="464.927" errors="3" timestamp="2023-08-12T18:45:21 ICT" skipped="0">
  <testcase classname="test.TestCases" name="tc_03" time="14.803">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_03]]>
    </system-out>
  </testcase> <!-- tc_03 -->
  <testcase classname="test.TestCases" name="tc_08" time="33.744">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_08]]>
    </system-out>
  </testcase> <!-- tc_08 -->
  <testcase classname="test.TestCases" name="tc_07" time="46.191">
    <error message="Expected condition failed: waiting for element to be clickable: By.xpath: //a[@role=&quot;menuitem&quot; and contains(text(),&quot;Trackers&quot;)] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: &#039;4.9.1&#039;, revision: &#039;eb2032df7f&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.8&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 115.0.5790.171, chrome: {chromedriverVersion: 115.0.5790.170 (cc0d30c2ca5..., userDataDir: C:\Users\Admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57425}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57425/devtoo..., se:cdpVersion: 115.0.5790.171, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 490203d195cb463520a0bb3a5b64ccbd" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //a[@role="menuitem" and contains(text(),"Trackers")] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 115.0.5790.171, chrome: {chromedriverVersion: 115.0.5790.170 (cc0d30c2ca5..., userDataDir: C:\Users\Admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57425}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57425/devtoo..., se:cdpVersion: 115.0.5790.171, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 490203d195cb463520a0bb3a5b64ccbd
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at function.CommonFunction.click(CommonFunction.java:31)
at function.PerformacePageFunction.searchPerformnaceTrackers(PerformacePageFunction.java:63)
at test.TestCases.tc_07(TestCases.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
    <system-out>
      <![CDATA[Đây là test case bị fail: tc_07]]>
    </system-out>
  </testcase> <!-- tc_07 -->
  <testcase classname="test.TestCases" name="tc_04" time="18.134">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_04]]>
    </system-out>
  </testcase> <!-- tc_04 -->
  <testcase classname="test.TestCases" name="tc_10" time="16.115">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_10]]>
    </system-out>
  </testcase> <!-- tc_10 -->
  <testcase classname="test.TestCases" name="tc_18" time="20.981">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_18]]>
    </system-out>
  </testcase> <!-- tc_18 -->
  <testcase classname="test.TestCases" name="tc_12" time="29.636">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_12]]>
    </system-out>
  </testcase> <!-- tc_12 -->
  <testcase classname="test.TestCases" name="tc_02" time="8.434">
    <error message="
Data Provider public static java.lang.Object[][] test.TestCases.getAccount() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public static java.lang.Object[][] test.TestCases.getAccount() returned a null value
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tc_02 -->
  <testcase classname="test.TestCases" name="tc_09" time="17.979">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_09]]>
    </system-out>
  </testcase> <!-- tc_09 -->
  <testcase classname="test.TestCases" name="tc_14" time="22.505">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_14]]>
    </system-out>
  </testcase> <!-- tc_14 -->
  <testcase classname="test.TestCases" name="tc_21" time="21.835">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_21]]>
    </system-out>
  </testcase> <!-- tc_21 -->
  <testcase classname="test.TestCases" name="tc_13" time="50.861">
    <error message="Expected condition failed: waiting for visibility of element located by By.xpath: //div[@role=&quot;option&quot;] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: &#039;4.9.1&#039;, revision: &#039;eb2032df7f&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.8&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 115.0.5790.171, chrome: {chromedriverVersion: 115.0.5790.170 (cc0d30c2ca5..., userDataDir: C:\Users\Admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57554}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57554/devtoo..., se:cdpVersion: 115.0.5790.171, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b0168939d953b8305ded6df5ad82d260" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //div[@role="option"] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 115.0.5790.171, chrome: {chromedriverVersion: 115.0.5790.170 (cc0d30c2ca5..., userDataDir: C:\Users\Admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57554}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57554/devtoo..., se:cdpVersion: 115.0.5790.171, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b0168939d953b8305ded6df5ad82d260
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at function.CommonFunction.sendkeysDropdownList(CommonFunction.java:103)
at function.PerformacePageFunction.searchManagePerformanceReviews(PerformacePageFunction.java:110)
at test.TestCases.tc_13(TestCases.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
    <system-out>
      <![CDATA[Đây là test case bị fail: tc_13]]>
    </system-out>
  </testcase> <!-- tc_13 -->
  <testcase classname="test.TestCases" name="tc_17" time="18.728">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_17]]>
    </system-out>
  </testcase> <!-- tc_17 -->
  <testcase classname="test.TestCases" name="tc_20" time="24.068">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_20]]>
    </system-out>
  </testcase> <!-- tc_20 -->
  <testcase classname="test.TestCases" name="tc_11" time="20.567">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_11]]>
    </system-out>
  </testcase> <!-- tc_11 -->
  <testcase classname="test.TestCases" name="tc_15" time="17.973">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_15]]>
    </system-out>
  </testcase> <!-- tc_15 -->
  <testcase classname="test.TestCases" name="tc_05" time="21.628">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_05]]>
    </system-out>
  </testcase> <!-- tc_05 -->
  <testcase classname="test.TestCases" name="tc_06" time="20.575">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_06]]>
    </system-out>
  </testcase> <!-- tc_06 -->
  <testcase classname="test.TestCases" name="tc_16" time="21.747">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_16]]>
    </system-out>
  </testcase> <!-- tc_16 -->
  <testcase classname="test.TestCases" name="tc_01" time="9.450">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_01]]>
    </system-out>
  </testcase> <!-- tc_01 -->
  <testcase classname="test.TestCases" name="tc_19" time="8.973">
    <system-out>
      <![CDATA[Đây là test case chạy thành công: tc_19]]>
    </system-out>
  </testcase> <!-- tc_19 -->
  <system-out>
    <![CDATA[Đây là đoạn khởi động auto test
Đây là test case chạy thành công: tc_01
Đây là test case bị fail: tc_02
Đây là test case chạy thành công: tc_03
Đây là test case chạy thành công: tc_04
Đây là test case chạy thành công: tc_05
Đây là test case chạy thành công: tc_06
Đây là test case bị fail: tc_07
Đây là test case chạy thành công: tc_08
Đây là test case chạy thành công: tc_09
Đây là test case chạy thành công: tc_10
Đây là test case chạy thành công: tc_11
Đây là test case chạy thành công: tc_12
Đây là test case bị fail: tc_13
Đây là test case chạy thành công: tc_14
Đây là test case chạy thành công: tc_15
Đây là test case chạy thành công: tc_16
Đây là test case chạy thành công: tc_17
Đây là test case chạy thành công: tc_18
Đây là test case chạy thành công: tc_19
Đây là test case chạy thành công: tc_20
Đây là test case chạy thành công: tc_21]]>
  </system-out>
</testsuite> <!-- test.TestCases -->
